### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by mattburman** [theWebby/PythonWordSearch#2]
************* Module classifier
C:104, 0: Trailing newlines (trailing-newlines)
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: Old-style class defined. (old-style-class)
W:  5, 0: Class has no __init__ method (no-init)
C: 27, 8: Invalid variable name "x" (invalid-name)
C: 36, 4: Invalid method name "learnPCA" (invalid-name)
C: 36, 4: Invalid argument name "N" (invalid-name)
C: 36, 4: Missing method docstring (missing-docstring)
E: 36, 4: Method should have "self" as first argument (no-self-argument)
E: 43,16: Instance of 'Classifier' has no 'shape' member (no-member)
C: 53, 8: Invalid variable name "u" (invalid-name)
C: 54, 8: Invalid variable name "d" (invalid-name)
C: 54,11: Invalid variable name "pc" (invalid-name)
E: 54,16: Unexpected keyword argument 'eigvals' in function call (unexpected-keyword-arg)
C: 55, 8: Invalid variable name "pc" (invalid-name)
W: 54, 8: Unused variable 'd' (unused-variable)
C: 64, 4: Invalid method name "reducePCA" (invalid-name)
C: 64, 4: Missing method docstring (missing-docstring)
E: 64, 4: Method should have "self" as first argument (no-self-argument)
************* Module found_word
C:  6, 0: Line too long (105/100) (line-too-long)
C: 30, 0: Line too long (101/100) (line-too-long)
C: 31, 0: Line too long (119/100) (line-too-long)
C: 44, 0: Line too long (108/100) (line-too-long)
C: 46, 0: Line too long (114/100) (line-too-long)
C: 59, 0: Line too long (109/100) (line-too-long)
C: 72, 0: Trailing newlines (trailing-newlines)
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Old-style class defined. (old-style-class)
R: 10, 4: Too many arguments (7/5) (too-many-arguments)
************* Module run_assignment
E: 27, 0: invalid syntax (syntax-error)
************* Module search
C: 11, 0: Line too long (106/100) (line-too-long)
C: 47, 0: Line too long (110/100) (line-too-long)
C: 54, 0: Line too long (104/100) (line-too-long)
C: 89, 0: Line too long (108/100) (line-too-long)
C: 96, 0: Line too long (104/100) (line-too-long)
C:103, 0: Line too long (102/100) (line-too-long)
C:129, 0: Line too long (119/100) (line-too-long)
C:142, 0: Line too long (111/100) (line-too-long)
C:146, 0: Trailing newlines (trailing-newlines)
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing class docstring (missing-docstring)
C:  4, 0: Old-style class defined. (old-style-class)
W:  4, 0: Class has no __init__ method (no-init)
C:  9, 4: Invalid argument name "x" (invalid-name)
C:  9, 4: Invalid argument name "y" (invalid-name)
C: 52, 4: Invalid argument name "x" (invalid-name)
C: 52, 4: Invalid argument name "y" (invalid-name)
C: 94, 4: Invalid argument name "x" (invalid-name)
C: 94, 4: Invalid argument name "y" (invalid-name)
************* Module word_search
E:170, 0: invalid syntax (syntax-error)

Report
======
131 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |3      |3          |=          |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |3      |3          |=          |66.67       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|method   |11     |11         |=          |81.82       |18.18    |
+---------+-------+-----------+-----------+------------+---------+
|function |0      |0          |=          |0           |0        |
+---------+-------+-----------+-----------+------------+---------+

External dependencies
---------------------
::

    found_word (search)
    matplotlib 
      \-pyplot (found_word)
    numpy (classifier)
    scipy 
      \-linalg (classifier)

Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |144    |44.31 |144      |=          |
+----------+-------+------+---------+-----------+
|docstring |75     |23.08 |75       |=          |
+----------+-------+------+---------+-----------+
|comment   |21     |6.46  |21       |=          |
+----------+-------+------+---------+-----------+
|empty     |85     |26.15 |85       |=          |
+----------+-------+------+---------+-----------+

Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |0        |=          |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |0.000    |=          |
+-------------------------+------+---------+-----------+

Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |40     |40       |=          |
+-----------+-------+---------+-----------+
|refactor   |1      |1        |=          |
+-----------+-------+---------+-----------+
|warning    |3      |3        |=          |
+-----------+-------+---------+-----------+
|error      |6      |6        |=          |
+-----------+-------+---------+-----------+

% errors / warnings by module
-----------------------------

+---------------+------+--------+---------+-----------+
|module         |error |warning |refactor |convention |
+===============+======+========+=========+===========+
|classifier     |66.67 |66.67   |0.00     |32.50      |
+---------------+------+--------+---------+-----------+
|word_search    |16.67 |0.00    |0.00     |0.00       |
+---------------+------+--------+---------+-----------+
|run_assignment |16.67 |0.00    |0.00     |0.00       |
+---------------+------+--------+---------+-----------+
|search         |0.00  |33.33   |0.00     |45.00      |
+---------------+------+--------+---------+-----------+
|found_word     |0.00  |0.00    |100.00   |22.50      |
+---------------+------+--------+---------+-----------+

Messages
--------

+-----------------------+------------+
|message id             |occurrences |
+=======================+============+
|line-too-long          |14          |
+-----------------------+------------+
|invalid-name           |14          |
+-----------------------+------------+
|missing-docstring      |6           |
+-----------------------+------------+
|trailing-newlines      |3           |
+-----------------------+------------+
|old-style-class        |3           |
+-----------------------+------------+
|syntax-error           |2           |
+-----------------------+------------+
|no-self-argument       |2           |
+-----------------------+------------+
|no-init                |2           |
+-----------------------+------------+
|unused-variable        |1           |
+-----------------------+------------+
|unexpected-keyword-arg |1           |
+-----------------------+------------+
|too-many-arguments     |1           |
+-----------------------+------------+
|no-member              |1           |
+-----------------------+------------+

Global evaluation
-----------------
Your code has been rated at 4.35/10 (previous run: 4.35/10, +0.00)

**Comment by dannycjones** [comment]
Yikes.

**Comment by mattburman** [comment]
Terrible, isn't it?

**Comment by theWebby** [comment]
Words cannot describe how much I hate you both.

**Comment by mattburman** [comment]
<3

**Comment by mattburman** [comment]
❤️
